name: angular_counter
description: A web app that uses angular_cubit

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  angular: ^6.0.0-alpha+1
  angular_cubit:
    path: ../../packages/angular_cubit

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
