name: flutter_cubit
description: An experimental Flutter library which exposes widgets that integrate with cubits. Built to work with package:cubit.
repository: https://github.com/felangel/cubit
issue_tracker: https://github.com/felangel/cubit/issues
homepage: https://github.com/felangel/cubit

version: 0.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cubit: ^0.0.3
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
